server {
    listen       80;
    listen  [::]:80;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    # Разрешённая загрузка файлов до 100 МБ
    client_max_body_size 100m;

    location / {
        try_files $uri $uri/ =404;
    }
}
